### ISSUE TITLE
О чем это приложение? 

### ISSUE THREAD

**Issue by tigrus** [bervr/CityGameApi#8]
Иногда бывает полезно написать базовую идею приложения в readme файле. Дело в том, что github полон репозиториев с названием "Test Task!"... Подобные названия сразу указывают на необходимость включить критическое мышление. 

Саму папку с приложением также стоит переименовать из drtt в что-то более говорящее.

**Comment by bervr** [comment]
Fixed. Переименовал, добавил описание в readme. Изначально этого не делал чтобы не спойлерить задание
